### ISSUE TITLE
Memory leak with high volume traffic

### ISSUE THREAD

**Issue by aiiksveryown** [yeti-switch/sems#10]
I have memory leak with this version, Memory fills rapidly and sems restarts. Maybe 4000 concurrent calls too high?
I have used valgrind to analyse, here is the result.

Nothing about this in sems log.
[valgrind-out.txt](https://github.com/yeti-switch/sems/files/5132871/valgrind-out.txt)

Pls tell me if you need any more details.

**Comment by dmitry-sinina** [comment]
As for me there are  no critical issues  in your valgrind output - few leaks related to config parsing. What SEMS version are you running and how many memory it use on 4k calls? Have you loaded di_log module or not?

**Comment by dmitry-sinina** [comment]
@aiiksveryown Have you routed calls through SEMS under valgrind or just start it and stop?

**Comment by aiiksveryown** [comment]
Yes I routed calls under valgrind. running 1.8.34, on 32core, 24GB ram. Ram usage Increases exponentially under high load, and sems restarts when ram is filled. This process repeats. di_log isn't loaded, should it be?

**Comment by aiiksveryown** [comment]
general {
    daemon = yes
    stderr = no
    syslog_loglevel = 0
    syslog_facility = LOCAL0

    node_id = 8

    shutdown_mode {
        code = 508
        reason = "Test"
        allow_uac = true
    }
    pcap_upload_queue = pcap
    rtp_receiver_threads = 8

    media_processor_threads = 16
    session_processor_threads = 16

    dead_rtp_time=30
}


signaling-interfaces {
    interface somename {
        default-media-interface = somename
        ip4 {
            sip-udp {
                address = 1.1.1.1
                port = 5060
                use-raw-sockets = off
            }
            sip-tcp {
                address = 1.1.1.1
                port = 5060
                connect-timeout = 2000
                static-client-port = on
                idle-timeout=900000
                use-raw-sockets = off
            }
        }
    }
    interface some-net {
        default-media-interface = some-net
        ip4 {
            sip-udp {
                address = 1.1.1.1
                port = 5060
                use-raw-sockets = off
            }
            sip-tcp {
                address = 1.1.1.1
                port = 5060
                connect-timeout = 2000
                static-client-port = on
                idle-timeout=900000
                use-raw-sockets = off
            }
        }
    }
}

media-interfaces {
    interface somename {
        ip4 {
            rtp {
                address = 1.1.1.1
                low-port = 16384
                high-port = 32767
                dscp = 46
                use-raw-sockets = off
            }
        }
    }
    interface some-net {
        ip4 {
            rtp {
                address = 1.1.1.1
                low-port = 16384
                high-port = 32767
                dscp = 46
                use-raw-sockets = off
            }
        }
    }
}

modules {
    module "mp3"{}
    module "opus"{}
    module "wav"{}
    module "gsm"{}
    module "ilbc"{}
    module "adpcm"{}
    module "l16"{}
    module "g722"{}
    module "g729bcg"{}

    module "registrar_client" {}
    module "sctp_bus"{}
    module "http_client" {
        resend_interval=5000
        resend_queue_max=10000

        destination "pcap" {
            mode=put
            urls={ http://example.com:8081/upload }
            on_success {
                action = remove
            }
            on_failure {
                action = requeue
            }
        }
    }
    module "session_timer"{}
    module "jsonrpc"{
        listen{
            address = 0.0.0.0
            port = 7080
        }
        server_threads=32
    }

    module-global "uac_auth" { }

    module "yeti" {
        management {
            address = example.com
            port = 4444
            timeout = 60000
        }
        core_options_handling = yes
    }
}

routing {
    application = yeti
}

**Comment by aiiksveryown** [comment]
`general {
daemon = yes
stderr = no
syslog_loglevel = 0
syslog_facility = LOCAL0

node_id = 8

shutdown_mode {
    code = 508
    reason = "Test"
    allow_uac = true
}
pcap_upload_queue = pcap
rtp_receiver_threads = 8

media_processor_threads = 16
session_processor_threads = 16

dead_rtp_time=30
}

signaling-interfaces {
interface somename {
default-media-interface = somename
ip4 {
sip-udp {
address = 1.1.1.1
port = 5060
use-raw-sockets = off
}
sip-tcp {
address = 1.1.1.1
port = 5060
connect-timeout = 2000
static-client-port = on
idle-timeout=900000
use-raw-sockets = off
}
}
}
interface some-net {
default-media-interface = some-net
ip4 {
sip-udp {
address = 1.1.1.1
port = 5060
use-raw-sockets = off
}
sip-tcp {
address = 1.1.1.1
port = 5060
connect-timeout = 2000
static-client-port = on
idle-timeout=900000
use-raw-sockets = off
}
}
}
}

media-interfaces {
interface somename {
ip4 {
rtp {
address = 1.1.1.1
low-port = 16384
high-port = 32767
dscp = 46
use-raw-sockets = off
}
}
}
interface some-net {
ip4 {
rtp {
address = 1.1.1.1
low-port = 16384
high-port = 32767
dscp = 46
use-raw-sockets = off
}
}
}
}

modules {
module "mp3"{}
module "opus"{}
module "wav"{}
module "gsm"{}
module "ilbc"{}
module "adpcm"{}
module "l16"{}
module "g722"{}
module "g729bcg"{}

module "registrar_client" {}
module "sctp_bus"{}
module "http_client" {
    resend_interval=5000
    resend_queue_max=10000

    destination "pcap" {
        mode=put
        urls={ http://example.com:8081/upload }
        on_success {
            action = remove
        }
        on_failure {
            action = requeue
        }
    }
}
module "session_timer"{}
module "jsonrpc"{
    listen{
        address = 0.0.0.0
        port = 7080
    }
    server_threads=32
}

module-global "uac_auth" { }

module "yeti" {
    management {
        address = example.com
        port = 4444
        timeout = 60000
    }
    core_options_handling = yes
}
}

routing {
application = yeti
}`

**Comment by aiiksveryown** [comment]
general {
        daemon = yes
        stderr = no
        syslog_loglevel = 0
        syslog_facility = LOCAL0

        node_id = 8

        shutdown_mode {
            code = 508
            reason = "Test"
            allow_uac = true
        }
        pcap_upload_queue = pcap
        rtp_receiver_threads = 8

        media_processor_threads = 16
        session_processor_threads = 16

        dead_rtp_time=30
    }


    signaling-interfaces {
        interface somenet {
            default-media-interface = somenet
            ip4 {
                sip-udp {
                    address = 1.1.1.1
                    port = 5060
                    use-raw-sockets = off
                }
                sip-tcp {
                    address = 1.1.1.1
                    port = 5060
                    connect-timeout = 2000
                    static-client-port = on
                    idle-timeout=900000
                    use-raw-sockets = off
                }
            }
        }
        interface some-net {
            default-media-interface = some-net
            ip4 {
                sip-udp {
                    address = 1.1.1.1
                    port = 5060
                    use-raw-sockets = off
                }
                sip-tcp {
                    address = 1.1.1.1
                    port = 5060
                    connect-timeout = 2000
                    static-client-port = on
                    idle-timeout=900000
                    use-raw-sockets = off
                }
            }
        }
    }

    media-interfaces {
        interface somenet {
            ip4 {
                rtp {
                    address = 1.1.1.1
                    low-port = 16384
                    high-port = 32767
                    dscp = 46
                    use-raw-sockets = off
                }
            }
        }
        interface some-net {
            ip4 {
                rtp {
                    address = 1.1.1.1
                    low-port = 16384
                    high-port = 32767
                    dscp = 46
                    use-raw-sockets = off
                }
            }
        }
    }

    modules {
        module "mp3"{}
        module "opus"{}
        module "wav"{}
        module "gsm"{}
        module "ilbc"{}
        module "adpcm"{}
        module "l16"{}
        module "g722"{}
        module "g729bcg"{}

        module "registrar_client" {}
        module "sctp_bus"{}
        module "http_client" {
            resend_interval=5000
            resend_queue_max=10000

            destination "pcap" {
                mode=put
                urls={ http://example.com:8081/upload }
                on_success {
                    action = remove
                }
                on_failure {
                    action = requeue
                }
            }
        }
        module "session_timer"{}
        module "jsonrpc"{
            listen{
                address = 0.0.0.0
                port = 7080
            }
            server_threads=32
        }

        module-global "uac_auth" { }

        module "yeti" {
            management {
                address = example.com
                port = 4444
                timeout = 60000
            }
            core_options_handling = yes
        }
    }

    routing {
        application = yeti
    }

**Comment by dmitry-sinina** [comment]
could you show **yeti.show.stats** command output from yet-cli?

**Comment by dmitry-sinina** [comment]
have you tried to upgrade system to latest version? Actual SEMS versions is:
```
ii  libsems1                            1.32.0                       amd64        SIP Express Media Server, shared library
ii  sems                                1.32.0                       amd64        SIP Express Media Server, very fast and flexible SIP media server
ii  sems-modules-yeti                   1.9.16core32                 amd64        YETI SBC application module for SEMS
```

**Comment by aiiksveryown** [comment]
yeti-cli:switch1> yeti.show.stats
    {   'AmSession': {   'AvgSessionNum': 5690,
                        'MaxSessionNum': 9234,
                        'SessionNum': 1440},
        'AmSessionContainer': {   'dead_sessions_count': 83,
                                'unclean_shutdown_enabled': False},
        'calls_show_limit': 10000,
        'localtime': 1599603374,
        'resource_control': {   'errors': 190,
                                'hits': 2326167,
                                'nextroute': 0,
                                'overloaded': 79483,
                                'rejected': 79483},
        'router': {   'cdr_writer': {   'auth_log_threads': [   {   'db_exceptions': 0,
                                                                    'queue_len': 0,
                                                                    'retry_queue_len': 0,
                                                                    'tried_cdrs': 121,
                                                                    'writed_cdrs': 122},
                                                                {   'db_exceptions': 0,
                                                                    'queue_len': 0,
                                                                    'retry_queue_len': 0,
                                                                    'tried_cdrs': 116,
                                                                    'writed_cdrs': 116}],
                                        'cdr_threads': [   {   'db_exceptions': 5,
                                                            'queue_len': 0,
                                                            'retry_queue_len': 0,
                                                            'tried_cdrs': 2013125,
                                                            'writed_cdrs': 2017575},
                                                        {   'db_exceptions': 0,
                                                            'queue_len': 1,
                                                            'retry_queue_len': 0,
                                                            'tried_cdrs': 20221,
                                                            'writed_cdrs': 2021157}],
                                        'name': 'cdr',
                                        'poolsize': 2},
                    'db_hits': 3621501,
                    'gps_avg': 12.4,
                    'gps_max': 236.0,
                    'gt_max': 14.419505,
                    'gt_min': 0.001806,
                    'hits': 3621483,
                    'master_pool': {   'check_transactions': 0,
                                        'connections': [   {   'exceptions': 0},
                                                            {   'exceptions': 0},
                                                            {   'exceptions': 0},
                                                            {   'exceptions': 0}],
                                        'exceptions': 0,
                                        'failed_connections': 0,
                                        'reconnect_attempts': 4,
                                        'total_connections': 4,
                                        'tps_avg': 13.4,
                                        'tps_max': 254.2,
                                        'transactions': 3621384,
                                        'tt_max': 4.53847,
                                        'tt_min': 0.001804},
                    'slave_pool': {   'check_transactions': 9328,
                                        'connections': [   {   'exceptions': 0},
                                                        {   'exceptions': 0},
                                                        {   'exceptions': 0},
                                                        {   'exceptions': 0}],
                                        'exceptions': 0,
                                        'failed_connections': 0,
                                        'reconnect_attempts': 0,
                                        'total_connections': 4,
                                        'tps_avg': 0.8,
                                        'tps_max': 0.8,
                                        'transactions': 129,
                                        'tt_max': 0.818544,
                                        'tt_min': 0.003033},
                    'uptime': 46684.0},
        'trans_layer': {   'rx_replies': 18180632,
                        'rx_requests': 11690660,
                        'tx_replies': 16160115,
                        'tx_replies_retrans': 376548,
                        'tx_requests': 10190664,
                        'tx_requests_retrans': 295501},
        'translator': {   'missed_response_configs': 13,
                        'unknown_code_resolves': 26,
                        'unknown_internal_codes': 0},
        'uptime': 46684.0}
    Took 0.0257 seconds

I will try to run again when the issue reoccurs, although we now have reduced traffic.
We are running stretch, and latest version from apt is 1.8.58-2, I have updated to this version. Still see the memory leaks at around 4500 sessions.

**Comment by dmitry-sinina** [comment]
consider to upgrade your OS to buster to have latest SEMS.

**Comment by aiiksveryown** [comment]
{   'AmSession': {   'AvgSessionNum': 3535,
                        'MaxSessionNum': 9155,
                        'SessionNum': 5836},
        'AmSessionContainer': {   'dead_sessions_count': 979,
                                'unclean_shutdown_enabled': False},
        'calls_show_limit': 10000,
        'localtime': 1601458440,
        'resource_control': {   'errors': 8,
                                'hits': 46139230,
                                'nextroute': 0,
                                'overloaded': 47140,
                                'rejected': 47140},
        'router': {   'cdr_writer': {   'auth_log_threads': [   {   'db_exceptions': 0,
                                                                    'queue_len': 0,
                                                                    'retry_queue_len': 0,
                                                                    'tried_cdrs': 336,
                                                                    'writed_cdrs': 340},
                                                                {   'db_exceptions': 0,
                                                                    'queue_len': 0,
                                                                    'retry_queue_len': 0,
                                                                    'tried_cdrs': 304,
                                                                    'writed_cdrs': 307}],
                                        'cdr_threads': [   {   'db_exceptions': 13847,
                                                            'queue_len': 543907,
                                                            'retry_queue_len': 6814,
                                                            'tried_cdrs': 8119002,
                                                            'writed_cdrs': 35747399},
                                                        {   'db_exceptions': 13876,
                                                            'queue_len': 544311,
                                                            'retry_queue_len': 6813,
                                                            'tried_cdrs': 28044940,
                                                            'writed_cdrs': 35750190}],
                                        'name': 'cdr',
                                        'poolsize': 2},
                    'db_hits': 72602002,
                    'gps_avg': 99.4,
                    'gps_max': 324.4,
                    'gt_max': 1.650309,
                    'gt_min': 0.001807,
                    'hits': 72601826,
                    'master_pool': {   'check_transactions': 11254,
                                        'connections': [   {   'exceptions': 0},
                                                            {   'exceptions': 0},
                                                            {   'exceptions': 0}],
                                        'exceptions': 0,
                                        'failed_connections': 0,
                                        'reconnect_attempts': 0,
                                        'total_connections': 4,
                                        'tps_avg': 99.4,
                                        'tps_max': 324.2,
                                        'transactions': 72602389,
                                        'tt_max': 1.650305,
                                        'tt_min': 0.001803},
                    'slave_pool': {   'check_transactions': 317224,
                                        'connections': [   {   'exceptions': 0},
                                                        {   'exceptions': 0},
                                                        {   'exceptions': 0},
                                                        {   'exceptions': 0}],
                                        'exceptions': 0,
                                        'failed_connections': 0,
                                        'reconnect_attempts': 0,
                                        'total_connections': 4,
                                        'tps_avg': 0.0,
                                        'tps_max': 0.0,
                                        'transactions': 0,
                                        'tt_max': 0.0,
                                        'tt_min': 0.0},
                    'uptime': 1586399.0},
        'trans_layer': {   'rx_replies': 325067599,
                        'rx_requests': 204532660,
                        'tx_replies': 312839515,
                        'tx_replies_retrans': 6944832,
                        'tx_requests': 190028750,
                        'tx_requests_retrans': 10465824},
        'translator': {   'missed_response_configs': 50,
                        'unknown_code_resolves': 100,
                        'unknown_internal_codes': 0},
        'uptime': 1586399.0}
    Took 0.0093 seconds

SEMS logs has `ERROR: Cant write record to master database` on repeat

This with the issue happening. I have deduced that this usually happens when there is some packet loss on a route, i.e >5% PL.
We also basically stop getting new CDRs from SEMS. 
I will consider the upgrade, but this is unlikely. Thanks

**Comment by dmitry-sinina** [comment]
SEMS project issue is not right place for such questions. Could you ask such questions at https://community.yeti-switch.org ?

**'db_exceptions': 13847,** indicates problems on database side, check your database logs.

**Comment by aiiksveryown** [comment]
okay
