### ISSUE TITLE
problem startibng sems on new installation

### ISSUE THREAD

**Issue by benoit7866** [yeti-switch/sems#4]
Hi,

I have a new install of yeti, done following the doc, but sems doesn't start, it fails with : 
[858/858] [yeti:cdr/TrustedHeaders.cpp:47] ERROR: pqxx_exception: ERROR:  function load_trusted_headers(unknown) does not exist
LINE 1: SELECT * FROM load_trusted_headers($1)
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

 [858/858] [yeti:cdr/TrustedHeaders.cpp:60] ERROR: can't load trusted headers config

**Comment by dmitry-sinina** [comment]
@benoit7866 ensure that you have 
```
routing {
        schema = switch15
```
at /etc/yeti/system.cfg as described at https://yeti-switch.org/docs/en/installation/management.html#etc-yeti-system-cfg

**Comment by benoit7866** [comment]
here is what i have in conf : 

signalling {
        globals {
                yeti {
                        pop_id = 4
                        msg_logger_dir = /var/spool/sems/dump
                        audio_recorder_dir = /var/spool/sems/record
                        audio_recorder_compress = true
                        log_dir = /tmp
                        routing {
                                schema = switch15
                                function = route_release
                                init = init


but still get [2205/2205] [yeti:yeti.cpp:113] DEBUG: fetching yeti module cfg
 [2205/2205] [yeti:cdr/TrustedHeaders.cpp:47] ERROR: pqxx_exception: ERROR:  function load_trusted_headers(unknown) does not exist
LINE 1: SELECT * FROM load_trusted_headers($1)
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

 [2205/2205] [yeti:cdr/TrustedHeaders.cpp:60] ERROR: can't load trusted headers config
 [2205/2205] [yeti:yeti.cpp:165] ERROR: TrustedHeaders configure failed
 [2205/2205] [yeti:SBC.cpp:147] ERROR: yeti configuration error

**Comment by dmitry-sinina** [comment]
@benoit7866 What version of yeti-web package you use? Have you initialized databases as described at https://yeti-switch.org/docs/en/installation/web.html#databases-data-initialization?

**Comment by benoit7866** [comment]
Hi,
I initialised the databases following the documentation, and the version of web interface is 👍 
Copyright 2018 Yeti Admin ver: 1.6.3. Routing ver 20180403104223. CDR ver 20180328123622.

taken from the repository described in documentation yesterday

**Comment by dmitry-sinina** [comment]
Try to connect(using psql) to routing database described at  /etc/yeti/system.cfg and check if function switch15.load_trusted_headers exists:
```
root@srv:~# psql -U username -h 127.0.0.1 -d databasename -p 5432
Password for user username: 

databasename=# \df switch15.load_trusted_headers
                                        List of functions
  Schema  |         Name         |        Result data type         | Argument data types |  Type  
----------+----------------------+---------------------------------+---------------------+--------
 switch15 | load_trusted_headers | TABLE(o_name character varying) | i_node_id integer   | normal
(1 row)

databasename=# 
```

**Comment by benoit7866** [comment]
It exists, i have the same result

**Comment by dmitry-sinina** [comment]
@benoit7866 
ok, I see only one possible cause:
If database described at  /etc/yeti/system.cfg contains function then sems use some old configuration
Have you restarted **yeti-management** daemon after changing system.cfg?

**Comment by benoit7866** [comment]
i maybe didn't restart. I just did it, now it goes further but still fails : 
 [6181/6219] [yeti:db/PgConnectionPool.cpp:224] DEBUG: PgCP  thread starting
 [6181/6219] [yeti:db/PgConnectionPool.cpp:250] DEBUG: PgCP: : start connection
 [6181/6221] [yeti:cdr/CdrWriter.cpp:523] ERROR: catched pqxx::failure: ERROR:  cannot pass more than 100 arguments to a function
LINE 1: SELECT writecdr($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$...
               ^
 [6181/6221] [yeti:cdr/CdrWriter.cpp:280] ERROR: can't connect to any DB on startup. give up
terminate called after throwing an instance of 'std::logic_error'
  what():  CdrWriter can't connect to any DB on startup
Aborted

**Comment by dmitry-sinina** [comment]
set     **serialize_dynamic_fields = true** in /etc/yeti/system.cfg as described at https://yeti-switch.org/docs/en/installation/management.html#etc-yeti-system-cfg then restart yeti-management and try again

**Comment by benoit7866** [comment]
Thanks, it is now starting.
