### ISSUE TITLE
build of dsm app failed

### ISSUE THREAD

**Issue by juha-h** [yeti-switch/sems#9]
I tried to to build dsm app by uncommenting app/CMakeLists.txt line
```
ADD_SUBDIRECTORY(dsm)
```
After that build failed like this:
```
make[3]: Entering directory '/home/jh/sems/build'
[ 74%] Building CXX object apps/dsm/CMakeFiles/sems_dsm.dir/DSM.cpp.o
cd /home/jh/sems/build/apps/dsm && /usr/bin/c++   -DLOG_BUFFER_LEN=2048 -DSESSION_THREADPOOL -DUSE_LIBSAMPLERATE -DUSE_MONITORING -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -Dsems_dsm_EXPORTS -I/home/jh/sems/core/ampi -I/home/jh/sems/core/amci -I/home/jh/sems/core -I/home/jh/sems/build/third/spandsp/src -I/home/jh/sems/build/third/botan/build/include -I/home/jh/sems/build/third/srtp/include -I/home/jh/sems/build/third/confuse/src  -g -O2 -fdebug-prefix-map=/home/jh/sems=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE -D_REENTRANT -Wall -Wno-reorder -fPIC -g -O2 -fPIC   -D__FILENAME__='"apps/dsm/DSM.cpp"' -DSEMS_APP_NAME='"sems"' -std=c++11 -Wno-deprecated -DMOD_NAME=\"dsm\" -o CMakeFiles/sems_dsm.dir/DSM.cpp.o -c /home/jh/sems/apps/dsm/DSM.cpp
/home/jh/sems/apps/dsm/DSM.cpp: In member function ‘int DSMFactory::preloadModules(AmConfigReader&, std::__cxx11::string&, const string&)’:
/home/jh/sems/apps/dsm/DSM.cpp:885:20: error: ‘class DSMModule’ has no member named ‘preload’
   if (last_loaded->preload()) {
                    ^~~~~~~
```
For some reason, public function
```
virtual int preload() { return 0; }
```
has been removed from DSMModule.h.

Why is that?  Or is dsm app simply not intended to work with yeti-switch sems?

**Comment by furmur** [comment]
> Or is dsm app simply not intended to work with yeti-switch sems?

correct, we do not use dsm app for yeti. and it stays here as legacy code.

it's possible to fix build of dsm app for actual core, but we see no reason to do it.

**Comment by dmitry-sinina** [comment]
@juha-h  Do you want to build sems for yeti or use it standalone?

**Comment by juha-h** [comment]
Dmitry Sinina writes:

> @juha-h  Do you want to build sems for yeti or use it standalone?

My plan was to check yeti-switch sems could be used standalone as
original iptel sems replacement.

As you probably know, no-one is currently in charge of iptel sems and it
would be nice to get a well maintained core for it.  There are still
some people who use the original sems with its sbc and dsm apps.

**Comment by juha-h** [comment]
Michael Furmur writes:

> it's possible to fix build of dsm app for actual core, but we see no
> reason to do it.

Would you accept pull requests to make build of the dsm app to work?

**Comment by furmur** [comment]
> Would you accept pull requests to make build of the dsm app to work?

sure. any input is appreciated

**Comment by juha-h** [comment]
Unfortunately, it turned out that differences between sems-server/sems and yeti-switch/sems are too large to easily make apps/dsm to compile.  For example, yeti-switch/sems apps/json doesn't support JsonRPCEvents.
